### ISSUE TITLE
Call to undefined function add_action when using a dependency based WordPress structure (e.g. Bedrock)

### ISSUE THREAD

**Issue by tombonez** [jofrysutanto/windsor#1]
Hi @jofrysutanto,

First of all, thanks for creating this awesome project, I can't wait to (hopefully) switch from ACF Builder as this looks like a much easier and cleaner way of using ACF with version control support 😃

Unfortunately it appears that ACF Windsors can't currently work with dependency based WordPress structures such as [Roots Bedrock](https://github.com/roots/bedrock), as add_action is called before the function exists.

Other projects such as [Timber](https://github.com/timber/timber#installation) get around this by having the user initialise it via functions.php.

Hopefully this is something you'd be willing to change as I'd love to use ACF Windsor moving forward.

Any questions or what not just let me know.

Cheers,
Tom 🙂

**Comment by jofrysutanto** [comment]
This is definitely something I am going to address, thanks for bringing it up!

At the moment the library is set to auto-initialize as a means of convenience. I am thinking of giving the flexibility for developers to defer this initialization, and leave it to developers to decide when to initialize the library. Which I think will solve the issue if you are using Bedrock.

I will play around with it using Bedrock, stay tuned.

Jofry.

**Comment by tombonez** [comment]
Awesome! Thanks a ton Jofry 😃

**Comment by jofrysutanto** [comment]
Resolved by #2 — feel free to take it for a spin @tombonez

**Comment by tombonez** [comment]
The latest release is working a treat, thanks again @jofrysutanto 😃
